# Generated by Django 4.2.16 on 2025-05-07 19:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scenelog",
            options={"managed": False},
        ),
    ]
