# Generated by Django 4.2.16 on 2025-05-07 19:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_scenelog_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="scenelog",
            table="scene_logs",
        ),
    ]
